@host = http://127.0.0.1:8000/api

@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIzIiwianRpIjoiNTFlN2UyZmQ2NzcyZjYwNWRhYWRiZTBkMzBhMTdlOWY1ZGNmYjI3NDk3MWIyZDYxMGQ4OWFkYmU2ZjI2N2RiYmZlNzY4MGQxNWRiZWEwMzYiLCJpYXQiOjE2OTIxODMzNDUuOTgyNDg4LCJuYmYiOjE2OTIxODMzNDUuOTgyNDksImV4cCI6MTcyMzgwNTc0NS45NzE5NCwic3ViIjoiMSIsInNjb3BlcyI6W119.jZ44HukfL4Y5eTTVvD_IKka7hhC-hwfempMGXKb6cjue0xKVsFZV4uBCOCn5kqc4aVqSDzPOtO90tkEPJT0UUFq_qSbkY3y_15SCdoPA4Hu_X9L7LZDQxvoWhZ2jOe0IG_xKCK1f6xOA7aADakyqGpHjmZ4sE3LW8u_52r1-wDjZm4vZTvecaH2XBnwWwd7Cwtp-E2Nln6gni_hArgKHdtI9SPw9Dioy1xbHhaGzFn-6mhlSQwkdw_YWS154RRLARm9RaR5nz5JCYz4VALqjKbhj4H2vvy--DdIvZU8UUARuc1kNF84onpJEpv1AcnfhwLLkSHEO62GbqFcfR9onXyUvFSiQRkAgKO4A7CY2Jbahdm3d-rSEcl2RKhO46rkBn0_ffX-yvFhKXZ1-J1JnC8Z1fJa4z2eQbPk4DZYNEaPE1ggn0n-y80vgDJuUg7bw2PHq5LpOpX4y0K9_4iHEgZbSICdoD28qD1mtnEcjVlmpU1lkhjmQhnTSU6S0hrlW9sDx4GXZp7j8OGv3YF8ijHHaw_xWG_fXWkVnCsvT87HiuURlriH5vDYCV60iovI8UsOSIKiaFSG2e2HhetOi3thMHFbdVuOk26mKJSPqYT3r4zENfL2HPMgLad01okHwWckFyaW2tzBvE4yNbte0rX0UmYP9q1pblxz8kUJlEyc
GET {{host}}/auth/user HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


################
## login user
POST {{host}}/auth/login HTTP/1.1
Content-Type: application/json
app-role: owner

{
  "email": "owner@gmail.com",
  "password": "passward"

}

################
## Logout
POST {{host}}/auth/logout HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{

}

################
## Employee Add
POST {{host}}/auth/add-employee HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
# app-role: employee

{

  "username": "moon1",
  "email": "moon1@gmail.com",
  "password": "123456"

}

################
## Employee List
GET {{host}}/employee/list HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
app-role: owner

{


}

################
## Employee Report List
GET {{host}}/employee/report HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
app-role: owner

{
    "email": "asdj@mail.com",
    "employee_id": 2,
    "is_pdf" : 1,
     "fromdate":"2023-08-13",
     "todate": "2023-08-15"

}


################
## Individual-Employee Report List
GET {{host}}/employee/individual HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
app-role: owner

{
      "employee_id": "7"
}


################
## Generate pdf Individual Employee Report List
GET {{host}}/employee/individual-pdf HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
app-role: owner

{
         "employee_id": "7"
}




