@host = http://127.0.0.1:8000/api

@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIzIiwianRpIjoiMjRkYzRjYWFhYmI1YjA5MmYwNTNiN2YzZmIzYWI4MjU1OTMxOTQwZjg4YzYxOTZiMTg1ZjZhNmZjZWE5YzNiZGU4N2Y4NDY3ZDFmNGU1M2MiLCJpYXQiOjE2OTE5OTU5NzUuNDg1Mzg0LCJuYmYiOjE2OTE5OTU5NzUuNDg1Mzg4LCJleHAiOjE3MjM2MTgzNzUuNDc1NDcxLCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.wWwbp80p3NprNJmD6oQEI5WjvCy4F5TtV5euz6g86PcPM3YI6tzZAf6ulxuSArURPt2sc6tC4-H-WzGQqBMxbxK9sDCFTQPb_Zjta8kCCA8EZZkOngS-23XZn6KEs7bFt_FhN0n-Trec3WLMgWf1JXfdGk9UBMOJanOJblkvUdpj_GmXYLHW6-y9RCucvGmMiXSOpgJ2n5h5-0MG1Dhuz5-grZrfpiVKyQVy-AIojNf9VQ2o8WhWzx_38tpBfKq3mS5Fgnya7D1xKQLAW5WlnVb3MqUe0_hGazVIqXo-8snoGokU0H2TirpSh6DvX29uWj-MFcUvJSeLq2FfijEXJ5ae6WBe3B7yUz_Af0aieQoiAXZXyHRTlTZOepcT_V3ojR_F-7vcSn55laZjmDr4RTQql40S13BFBXecS4sX18Auw7hsMyjyd4Dh9Gc3kcXyRIiHQGP_JGG0ZDEN3d8Pn9hg1dSWYeoMUG_meWQpcIzjmhz4la6yWLCfH4_Ek8V1zh4t9izUaEp2RymUbHPv6-lyna880w-iud44tpvpMaIg5IXV4Wo_C79Qn5W6tD57c5tO3AvpiVemIQowHdMCFoayFl0ZaSODV0NvrgamAD0HawQAtwVEfEnfYLbVwARkb4-k4DVEVUkIj8KF3bhXwAfxI_8B-bgU5hF2hoHTyIQ
GET {{host}}/auth/user HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


################
## login user
POST {{host}}/auth/login HTTP/1.1
Content-Type: application/json
app-role: owner

{
  "email": "owner@gmail.com",
  "password": "passward"

}

################
## Logout
POST {{host}}/auth/logout HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{

}

################
## Employee Add
POST {{host}}/auth/add-employee HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
# app-role: employee

{

  "username": "moon1",
  "email": "moon1@gmail.com",
  "password": "123456"

}

################
## Employee List
GET {{host}}/employee/list HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
app-role: owner

{


}

################
## Employee Report List
GET {{host}}/employee/report HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
app-role: owner

{
          "todate": "2023-08-13"
}

################
## Employee Report List From Date
GET {{host}}/employee/report-fromdate HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
app-role: owner

{
          "todate": "2023-08-12",
          "fromdate": "2023-08-13"
}

################
## Individual-Employee Report List
GET {{host}}/employee/individual HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
app-role: owner

{
      "employee_id": "7"
}

################
## Generate pdf Employee Report List From Date
GET {{host}}/employee/generate-pdf HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
app-role: owner

{
         "todate": "2023-08-11",
         "fromdate": "2023-08-13"
}

################
## Generate pdf Individual Employee Report List
GET {{host}}/employee/individual-pdf HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
app-role: owner

{
         "employee_id": "7"
}




