@host = http://127.0.0.1:8000/api

@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIzIiwianRpIjoiZTc1NTIxYmNkMDdiMWM0MzQyNmZlNGQ3ZDgxZWVjNzQzNDA1ZjY2MGExZDYzM2FkYmE5MmY3NWQ5NGI4ZGNkNjUyZjEyMGNlOTc0MGY5NmUiLCJpYXQiOjE2OTI3ODcyMTAuMDgyNTk3LCJuYmYiOjE2OTI3ODcyMTAuMDgyNTk5LCJleHAiOjE3MjQ0MDk2MTAuMDc0Nzg0LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.Vu9t7SmQWj7H_F8CAkUwIvvt3pYRPbDmexUS0H1vitytakiJKiO0fVZQILdXiSWO5GkyKEV2vkLwNXhtyV_Grg0CkVoYINNzZRLlgxskOzqZhCumZHCnbecQ7L3ltaLJIoAkmVWJ2VzeO3lzfIsXTsGs_KDURul2tvu0ot1-uium_LyMVupbTX5BPMqHsFaL3ibqmnKv-ve7t2I2KOXrNXfrqWvzjmpwMoDwonXqTArdZaKjrrMBNhpgvw0A5huJ3EsMLdncuGIMC0P2_gUE3VMBTZe642a6m3D78lGva8jrrAV5PDgOOIuIAX8sr9vZYT9rgQn8tZzXsaLhuv9Z-15FZreWKUpPAVBwDqFP6K9vs0cL12GeKIYhV0jjSYujJmY4TIs1puZJZn1IDnvJzooJdVM-qNXBybQgPQczTQK6c5di6sbfwy81kJO0hrHGzRcQYPaW_LwLCI4ISjaZjb7Vf0kCm_GXbSAx0tFFotXIfYQ1k8Ne8GRHszDmKH2uTWEe3FhPDBGRetLmZtCCo9-OTQTkASF6BETwYLYlO6ig4i5QgF0M2pmUQ5jWX0wD7Sw4ZF1jgvVgokFLfepfdrix3lh0w8-TROWgjmFej6W4OiOKnp5YDowYs1wJgdHOvKnIZW5deKiq0Q9s5bZtD9-71eQ60UKS9NyIhEX1GQ4

GET {{host}}/auth/user HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


################
## login user
POST {{host}}/auth/login HTTP/1.1
Content-Type: application/json
app-role: owner

{
  "email": "owner@gmail.com",
  "password": "passward"

}

################
## Logout
POST {{host}}/auth/logout HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{

}

################
## Employee Add
POST {{host}}/auth/add-employee HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
# app-role: employee

{

  "username": "Jeri",
  "email": "jeri1@gmail.com",
  "password": "123456",
  "designation": "developer"

}

