@host = http://127.0.0.1:8000/api
# @host =https://ems.ctgsociety.org/api

@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNDk3ODc1YjhiMTY0ZGNhMTFlMWQ5OGJjYTdkZGJlNzEzYzc0OGY5Y2ZiNWU2NjkwMDdjZWY5ZmI3MzIzZGNmNDIyMzM3MTJhNjdmMDRkNzYiLCJpYXQiOjE2OTQ0MDkxMjMuNDU5NDM5LCJuYmYiOjE2OTQ0MDkxMjMuNDU5NDQxLCJleHAiOjE3MjYwMzE1MjMuNDUwODM2LCJzdWIiOiI0Iiwic2NvcGVzIjpbXX0.jw9XLcn25xuIdp7jpcFj-I-qbegm-6j06b7zPVuCBaXsQ4GO-VZgbH9uVDkCu6pdjz76_z9lbf4c2DHZCL1is74GJFsJTJzjHtAWlcN6p1AzIPo18KN1UelVIBcUr_4I_D_W7s1dI1mumu3D9gPzTwYGWtjGL1xe_LPzyFT7czC91zKTDoBJ5khI-bWCFWnqlLie6KZXS4DHSI9x-4sZfnav4gHPO8CUfxwa-yr5Z4ovOR-Nno2FlUXM-in2RYL-Iex-ik3oGkXChlPccuqEvR5bKiYO1wj6Azcmlm2_QEXzQ5WZriFvz6ltzyjWeb5IuFBJlguY8E7bGg6o2iVPGs_AxBfooL4ZWwbdsUU9ZV9mSOtbIpLRyzj_9gofoOjttkbsUEBPzPCjxyV7CHy-sd4saR2WRD1bKuuWlb5q5K176SP198TyKwf8UktFHJ_VXfDbCot41E-_V5M60OyQ375qj8QgvY5gOFmkh0XmRvozvcu7dEamUXp8YKPeE8uwdEefxUkYF-YYAOQ-8qTh_hgw16VjH_BEZfLKk-WVBMafBmpftkEUHu_93PYbPaEviDelWkB65UfvXlsGFCb0wVKPM4h-puvXUVU0-WJbbyIxHG9Y7MX9OW0W36bHVXkXgreliTMb623TLeCauvIuP5UoHjep47gRL7ITIr7O9rM
### User Details
GET {{host}}/auth/user HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


################
## login user
POST {{host}}/auth/login HTTP/1.1
Content-Type: application/json
app-role: employee

{
  "email": "karimaddzg@gmail.com",
  "password": "123456"

}

################
## Logout
POST {{host}}/auth/logout HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{

}

################
## Check In
POST {{host}}/employee/checkin HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
app-role: employee

{


}

################
## Start Break
POST {{host}}/employee/start-break HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
app-role: employee

{


}

################
## End Break
POST {{host}}/employee/end-break HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
app-role: employee

{


}

################
## Check out
POST {{host}}/employee/checkout HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
app-role: employee

{


}

################
## show auth project list
GET {{host}}/employee/auth-project-list HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
app-role: employee

{


}
################
## Add task
POST {{host}}/employee/task/add HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
app-role: employee

{
    "project_id": 2,
    "title": "Task Title",
    "description": "Task Description",
    "dependency": "Dependency Value",
    "delay_reason": "Reason for Delay",
    "start_date": "2023-09-05",
    "end_date": "2023-09-10",
    "status": "to_do"
}
################
## show auth task list
GET {{host}}/employee/task/list HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
app-role: employee

{



}

### Update auth task list
POST {{host}}/employee/task/update
content-type: application/json
app-role: owner
Authorization: Bearer {{token}}

{
    "id": 9,
    "project_id": 1,
    "title": "Task -Api Development section",
    "description": "Task Description",
    "dependency": "Dependency Value",
    "delay_reason": "Reason for Delay",
    "start_date": "2023-09-05",
    "end_date": "2023-09-10",
    "status": "on_going"
}

### delete auth task list
POST {{host}}/employee/task/delete HTTP/1.1
content-type: application/json
app-role: owner
Authorization: Bearer {{token}}

{
    "id": 9
}








