@host = http://127.0.0.1:8000/api
# @host =https://ems.ctgsociety.org/api

@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIzIiwianRpIjoiZWYxMzY0YWRkMjhmNzFjOTQ1NjdjMGQwYmZmYTQ0N2Y1N2U1MjM5MzBjN2I2ZGNjMmQ2ZDEyYjVhMjI5YjM3Y2UwNjQyYWE0MWIyMjg3YTMiLCJpYXQiOjE2OTQzNjQ1NDMuMDUxNzY2LCJuYmYiOjE2OTQzNjQ1NDMuMDUxNzY4LCJleHAiOjE3MjU5ODY5NDMuMDQ0Njk3LCJzdWIiOiI1Iiwic2NvcGVzIjpbXX0.qIkqH7cA3D0zXVhr5Obd01HQjPG5yKX5PzKfPonKtIIuYGbqdLD4gg7vdvpzaiOOFDLxSY_LLndD-nQGeiRcp17SITy2zU8GRed8dE7-Va9gx3xbS3NmerSuUeuzzQijSBWfbfXXQTlRDAPjrpFnN4xe9VoS2HNFD_YsF2ZhBCfEjdPfYgXpnn0n-oW_4P3ApUPe2ww78Pz7PWfifG2GAboM1kEpYItIESEJqAx8_zZiDR_ptHHjbe-pcnvZsorZb5KdGVdQccuYW0VMdfvIfUvW_x5WB8PGh19zKbmJwyP8O4so-cv-cFfaJpxp5h5CcQqcjISzdhRm_rvjPJwTkNt-XPZPN9Z_AZgeEehAFA416SvoJxPK3DJbBWJQlZz5xx5B4J3PtiGARfgcCb_TmC8qNxSQuWHD7vp1_4WJM6-u-peTClJDi6ksjbJ5dFNCCcqZ-_m-0gE2V6UPSRFNJ4zgPKyPnQvw4EDQfGdtaeYRZAmeo7cJhT4ITtpO-YzoizRC1uTk9dg91LjTvEtYmTeU0LWrywvpCqUOLaCVDLqw3EwhhgIGndOqW6uRQzUvWNAAm5VNU6tYwX1edLtj_TfOGYOzUGCI5EYfA5EYBf3MHmtUGslxP2U3XwyaszZvDnXwIFScV3MtlxAGYr356AMyUzj-71_SMypF7nuWYeU

### User Details
GET {{host}}/auth/user HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


################
## login user
POST {{host}}/auth/login HTTP/1.1
Content-Type: application/json
app-role: employee

{
  "email": "karimaddddzg@gmail.com",
  "password": "123456"

}

################
## Logout
POST {{host}}/auth/logout HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{

}

################
## Check In
POST {{host}}/employee/checkin HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
app-role: employee

{


}

################
## Start Break
POST {{host}}/employee/start-break HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
app-role: employee

{


}

################
## End Break
POST {{host}}/employee/end-break HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
app-role: employee

{


}

################
## Check out
POST {{host}}/employee/checkout HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
app-role: employee

{


}

################
## show auth project list
GET {{host}}/employee/auth-project-list HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
app-role: employee

{


}
################
## Add task
POST {{host}}/employee/task/add HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
app-role: employee

{
#    "employee_id": 5,
    "project_id": 2,
    "title": "Task Title more",
    "description": "Task Description",
    "dependency": "Dependency Value",
    "delay_reason": "Reason for Delay",
    "start_date": "2023-09-05",
    "end_date": "2023-09-10",
    "status": "to_do"
}
################
## show auth task list
GET {{host}}/employee/task/list HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
app-role: employee

{



}

### Update auth task list
POST {{host}}/employee/task/update
content-type: application/json
app-role: owner
Authorization: Bearer {{token}}

{
    "project_id": 4,
    "title": "Task -Api",
    "description": "Task Description",
    "dependency": "Dependency Value",
    "delay_reason": "Reason for Delay",
    "start_date": "2023-09-05",
    "end_date": "2023-09-10",
    "status": "on_going"
}

### delete auth task list
POST {{host}}/employee/task/delete HTTP/1.1
content-type: application/json
app-role: owner
Authorization: Bearer {{token}}

{
    "id": 4,
}








