@host = http://127.0.0.1:8000/api

@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNDg3NjUzNzYwY2IzZGQ0YmI5YzUxMTk0ZjRjNmQwNmY3ZGViNzM4NmI4YjlkOTcyMWZjMWJjZTYwYjMxZGM4NzBjMjAzNTc1ZTk1MDNkYzkiLCJpYXQiOjE2OTM5MDU1MjAuNzIzODQ3LCJuYmYiOjE2OTM5MDU1MjAuNzIzODUzLCJleHAiOjE3MjU1Mjc5MjAuNzE3MzM0LCJzdWIiOiIxMyIsInNjb3BlcyI6W119.q2aKfX4rzlKlz-n44UrF9cXexO4FhLRdqP5Hm9YMAqvpRtWlmE_aNSUuTZ8tEvalLS-xIyKBCb3XwKYVU14fCqLu9mXmqOOVcdUVEYolIqeFGdO9RMTHBvG3iXpkX6L9_LxCssFVF4wHfvrJNVjdc9p2QZvGGWBNXrlFyoa7iNZjddB_xCpdhMCHac1Y92H1UCIhaKbol1mjG7PG-CjT2mEkshybpsXWWlaG1YphJwzdOdvL8sFOes36K6AJxD0iKMtN8zGLWsepbZlB0s8hzk2HlVCS9K0ryegR42CQhm_KQECVfRNYZ57bMbmzjhei4rt6ogZ6XVUr2tzOgkrxu6s3qQwmmtmCiW-eztE9Pw7RgK6hlEEnzbRVawriG1xVZeqbNgtzVer4MlWevfMaBPZG8aeW7eCSyTYcBYSwuqNQgxr6jfYKzMneUZm88nPOhIR1wEnE82q1W2JcwV0D5xg0RZ9q-4ZTW5IeJAVERqJL8tzxIZb0KK8gSvgOFeHgA7oX1DUgxbTe-Rmf6_0zuwClEqCp0CiIBePBqSzoXAV31Y2moi4lqFpkgMfiaLEnvUkeQc62d5mKeqvDV5jA8vHZ_PtZPhQ8KthPJxfNt9S4Aw71AwAG0ZBGSRoqOJdX6k_g9nY9IV4Xi9vWmXhbECIYJteNzCgQ2RGEftyzwq0
GET {{host}}/auth/user HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


################
## login user
POST {{host}}/auth/login HTTP/1.1
Content-Type: application/json
app-role: employee

{
  "email": "jeri1@gmail.com",
  "password": "123456"

}

################
## Logout
POST {{host}}/auth/logout HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{

}

################
## Check In
POST {{host}}/employee/checkin HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
app-role: employee

{


}

################
## Start Break
POST {{host}}/employee/start-break HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
app-role: employee

{


}

################
## End Break
POST {{host}}/employee/end-break HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
app-role: employee

{


}

################
## Check out
POST {{host}}/employee/checkout HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
app-role: employee

{


}

################
## Add task
POST {{host}}/employee/task/add HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
app-role: employee

{
    "title": "Task Title",
    "project_id": 1,
    "description": "Task Description",
    "dependency": "Dependency Value",
    "delay_reason": "Reason for Delay",
    "start_date": "2023-09-05",
    "end_date": "2023-09-10"
}







