@host = http://127.0.0.1:8000/api

@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIzIiwianRpIjoiOTg0MTk5ODRlMjk5NGQwZjFhOTFiOGE4MzhiNWUwMTA1N2Y2MDM3ZjE3ZjhlMzYxNzdlZjlkMmUyZTQxYTRmMGM1YTk5MjQ4Y2I1ZWE5ZTgiLCJpYXQiOjE2OTI3MDA5MDUuMTM4MDI1LCJuYmYiOjE2OTI3MDA5MDUuMTM4MDI4LCJleHAiOjE3MjQzMjMzMDUuMTMwNzQ0LCJzdWIiOiIxMCIsInNjb3BlcyI6W119.bndtwBtJE8aj9L99FNMOMKnIapMwKu7sC8m589pcKhP93gCCoM7OUHqxZqzXzQfprzqTFepYxEVjdYwq9WykOJlmCi_q0P02HyZCk4OCoAhN-UeUEXX0jAKfDRH9Hl_E_4a37VQTydoG8mga-AKTdG6qDtMP_ExIpdydk_dmjzp-WOZ9psEahm32nZkPuyqw7DJx5p2gwk4yv6MWz9hYPpyL0yCGBY4TKaGXvtM_0Ke-KT4sPUj9YmLZKSxFCKSXP_i4bj2D4kiHpD_1SVRH8BG2xAT37d8alY2eDeUUZu90DiQk6E5HNaNw_9ip2ThSo1IwfTs1YxlGd1jvpSCI0-haJ_KDmV93hO3GI5SkuV9gfSvT0icVLaYgeoQZpVQ4iPs_vcNiGXhbhilDkj7QHiv1o1dCOvilJEeJkjBsrE1X6GsI-acXw7J6TKX2IMaogJjnLOQ0v9quw8aXNcKtbOIgUso7acPzcu6Xr_wPT7PCbrYm3r8K9-fR_s_4uqMXCMFDyvDbqWTsfyz6qaNjmhXMMeN11c5sJB2mZa57Ib1qH8K_H0xXLuxfC-c8xt8wsJNLoZa6hkmWsfM1kKqhtGumhBAZ0fNgbXVZgx3A4FjF-yxHHE5T_YGMnsgkZ4xfNmMoZZKvs9OOhuqkOCReGl4Gn7VanYE_sQ7KRBNJdKQ
##get user
GET {{host}}/auth/user HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


################
## login user
POST {{host}}/auth/login HTTP/1.1
Content-Type: application/json
app-role: employee

{
  "email": "moon1@gmail.com",
  "password": "123456"

}

################
## Logout
POST {{host}}/auth/logout HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{

}

################
## Check In
POST {{host}}/employee/checkin HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
app-role: employee

{


}

################
## Start Break
POST {{host}}/employee/start-break HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
app-role: employee

{


}

################
## End Break
POST {{host}}/employee/end-break HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
app-role: employee

{


}

################
## Check out
POST {{host}}/employee/checkout HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
app-role: employee

{


}







