@host = http://127.0.0.1:8000/api

@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIzIiwianRpIjoiOTRiMTdhYzMxODhjOTA3YmNiNzFiYzYzYjQ2YmQ4ZTAwYWUxZTcwMWY4YjA0N2Y3MWVlZDgyYzE0YWYxMmUxZWY5NzYxZTMyNmNhYzI0Y2EiLCJpYXQiOjE2OTI1MjgwNDMuMDAzMjE3LCJuYmYiOjE2OTI1MjgwNDMuMDAzMjE5LCJleHAiOjE3MjQxNTA0NDIuOTk2MjYyLCJzdWIiOiI1Iiwic2NvcGVzIjpbXX0.H9hBZNax2Adf9iscR8CYepvg81au8MhnJsU5mOmbUIVdIRXdNFCYMZyKvgtWbVHxtVf3jenPMIWoM9YmMxGIvE_dcdHRC3CQcZV3LXdCOa348tElOSo3L4tEMBfJ19vVNlp6TkASVwhgmn8BhbmO-jjKFDJhFbvBjviiGHJQMC5JpSupTlrw9RiLVhTU5cX_SlGHTibsasWiwJJE7ze7JC3-QnuIwtfzGlkN8Hb1_MZIBRTCCPImoqgeTJalt4aoVnfzFXKs57vnAoAc0eKEX8PQUzihyS9XeaiuWmLppFSNmJ6DjTRPvb0wMQTmTlGWU0FsXdUTSSVJdVxGWgevFukjl73iMeUFka_X09lfUbH1PzMoULgm2I4kh1bV_IOZaTQkefUH8pNQA19RUCKldWn4M3JFI5W2Pp7IgG9v6GvJwJMbH79DjsJsu2i2jd-4YssH0U2xCNpZoC-U5zBU_xrA4mYlMWfJ3Jioot1nH-nRiX1IukWht2PyoUOLvz8UHKEr7AfqRrKgb9nEjKi3aHPe6PTsQ-egE5QsjE6taVjmCpvfTPd8fZiyoZsxezabmuq0j0sW7NbAbUwJfPvzfYH59nGlHi1W-yLjic0-j4XQs8pTc4hMS-eaRY3497ZTpLJKjiwzLqc8FZvrx40SxuD_kNlGCQS7UZ3C0LwsKHc
##get user
GET {{host}}/auth/user HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


################
## login user
POST {{host}}/auth/login HTTP/1.1
Content-Type: application/json
app-role: employee

{
  "email": "karimaddddzg@gmail.com",
  "password": "123456"

}

################
## Logout
POST {{host}}/auth/logout HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{

}

################
## Check In
POST {{host}}/employee/checkin HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
app-role: employee

{


}

################
## Start Break
POST {{host}}/employee/start-break HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
app-role: employee

{


}

################
## End Break
POST {{host}}/employee/end-break HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
app-role: employee

{


}

################
## Check out
POST {{host}}/employee/checkout HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
app-role: employee

{


}







